<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto

namespace Task;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>task.UpdateTaskStatusRequest</code>
 */
class UpdateTaskStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 task_id = 1;</code>
     */
    protected $task_id = 0;
    /**
     * Generated from protobuf field <code>.task.Task.TaskStatus status = 2;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $task_id
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Task::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 task_id = 1;</code>
     * @return int
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>int32 task_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt32($var);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.task.Task.TaskStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.task.Task.TaskStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Task\Task\TaskStatus::class);
        $this->status = $var;

        return $this;
    }

}

